# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box settings
  config.vm.box = "ubuntu/xenial64"

  # Provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Network settings
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Open these ports as needed for use with forexample BrowserSync
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  # config.vm.network "forwarded_port", guest: 3001, host: 3001
  # config.vm.network "forwarded_port", guest: 3002, host: 3002

  # Synced folder
  config.vm.synced_folder "./data", "/var/www/html" , type: "nfs", create: true

  # Provisions #

  # Run commands as root
  config.vm.provision "shell", path: "install.sh"

  # Run commands as user
  config.vm.provision "shell", path: "wp.sh", privileged: false
end
